name: CI Pipeline Escuela Cafe

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Configurar Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: '20'

      - name: Instalar dependencias Backend
        working-directory: ./backend/backend
        run: npm ci

      - name: Correr Linter Backend
        working-directory: ./backend/backend
        run: npm run lint

  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Configurar Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: '20'

      - name: Instalar dependencias Frontend
        working-directory: ./frontend
        run: npm ci

      - name: Correr Linter Frontend
        working-directory: ./frontend
        run: npm run lint